version: "3.10"

services:

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - "./postgres:/var/lib/postgresql/data"

  redis:
    image: redis:latest
    restart: always

  app:
    build: .
    volumes:
      - .:/config
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8012:8012"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn config.wsgi:application -w 4 -b 0.0.0.0:8012"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/config
    env_file:
      - .env
    depends_on:
      - db
      - redis
