version: "3.10"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - "./postgres:/var/lib/postgresql/data"

  app:
    build: .
    volumes:
      - .:/config
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - "8020:8020"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn config.wsgi:application -w 4 -b 0.0.0.0:8020 --timeout 300"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - elasticsearch

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/config
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local
