# Generated by Django 4.2 on 2024-07-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_category_options_remove_category_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='product_images', verbose_name='Картинка'),
        ),
    ]
