# Generated by Django 4.2 on 2024-06-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dosage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дозировка'),
        ),
        migrations.AddField(
            model_name='product',
            name='dosage_form',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма выпуска'),
        ),
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Срок годности'),
        ),
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='В упаковке'),
        ),
    ]
