# Generated by Django 4.2 on 2024-07-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=1000, upload_to='product_images', verbose_name='Картинка'),
        ),
    ]
