# Generated by Django 4.2 on 2024-06-24 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_product_dosage_product_dosage_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='contraindications',
            field=models.TextField(blank=True, null=True, verbose_name='Противопоказания'),
        ),
        migrations.AddField(
            model_name='product',
            name='side_effects',
            field=models.TextField(blank=True, null=True, verbose_name='Побочные действия'),
        ),
        migrations.AlterField(
            model_name='dosageform',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_dosage_forms', to='medicine.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='indication',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_indications', to='medicine.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_purposes', to='medicine.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_volumes', to='medicine.product', verbose_name='Продукт'),
        ),
    ]
