# Generated by Django 4.2 on 2024-07-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ostatok',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Остаток'),
        ),
    ]
