# Generated by Django 4.2 on 2024-06-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_product_composition_product_contraindications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_rules',
            field=models.TextField(blank=True, null=True, verbose_name='Правила хранения'),
        ),
    ]
