# Generated by Django 4.2 on 2024-06-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_product_discount_percent_product_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Основное изображение'),
        ),
    ]
