# Generated by Django 4.2 on 2024-06-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0011_product_related_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, to='medicine.product', verbose_name='Похожие продукты'),
        ),
    ]
