# Generated by Django 4.2 on 2024-06-25 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0013_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 25, 10, 17, 34, 323554, tzinfo=datetime.timezone.utc), verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
