# Generated by Django 4.2 on 2024-06-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0015_recentlyviewedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_product_of_the_day',
            field=models.BooleanField(default=False, verbose_name='Товар дня'),
        ),
    ]
