# Generated by Django 4.2 on 2024-06-26 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('medicine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная сумма заказа')),
                ('bonus_points', models.PositiveIntegerField(verbose_name='Бонусные баллы')),
            ],
            options={
                'verbose_name': 'Конфигурация бонусов',
                'verbose_name_plural': 'Конфигурации бонусов',
            },
        ),
        migrations.CreateModel(
            name='DeliveryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Стоимость доставки')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Порог бесплатной доставки')),
            ],
            options={
                'verbose_name': 'Конфигурация доставки',
                'verbose_name_plural': 'Конфигурации доставки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('courier', 'Курьер'), ('pickup', 'Самовывоз')], max_length=20, verbose_name='Способ доставки')),
                ('payment_method', models.CharField(choices=[('online', 'Онлайн'), ('on_delivery', 'При доставке')], max_length=20, verbose_name='Способ оплаты')),
                ('delivery_time_choice', models.CharField(choices=[('immediate', 'Как можно скорее'), ('scheduled', 'Запланированная доставка')], default='immediate', max_length=20, verbose_name='Выбор времени доставки')),
                ('scheduled_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время доставки')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'Обрабатывается'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order_number', models.CharField(max_length=6, unique=True, verbose_name='Номер заказа')),
                ('used_bonus_points', models.PositiveIntegerField(default=0, verbose_name='Использованные бонусные баллы')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.useraddress', verbose_name='Адрес доставки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicine.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
    ]
