# Generated by Django 4.2 on 2024-06-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderitem_options_remove_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('courier', 'Курьер'), ('pickup', 'Самовывоз')], default=1, max_length=20, verbose_name='Способ доставки'),
            preserve_default=False,
        ),
    ]
