# Generated by Django 4.2 on 2024-06-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_status_delete_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Онлайн'), ('on_delivery', 'При доставке')], default=1, max_length=20, verbose_name='Способ оплаты'),
            preserve_default=False,
        ),
    ]
