# Generated by Django 4.2 on 2024-06-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time_choice',
            field=models.CharField(choices=[('immediate', 'Как можно скорее'), ('scheduled', 'Запланированная доставка')], default='immediate', max_length=20, verbose_name='Выбор времени доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время доставки'),
        ),
    ]
