# Generated by Django 4.2 on 2024-06-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_delivery_time_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time_choice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='scheduled_delivery_time',
        ),
    ]
