# Generated by Django 4.2 on 2024-06-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_delivery_time_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=1, max_length=6, unique=True, verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
