# Generated by Django 4.2 on 2024-06-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_order_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная сумма заказа')),
                ('bonus_points', models.PositiveIntegerField(verbose_name='Бонусные баллы')),
            ],
            options={
                'verbose_name': 'Конфигурация бонусов',
                'verbose_name_plural': 'Конфигурации бонусов',
            },
        ),
    ]
