# Generated by Django 4.2 on 2024-06-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_bonusconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='used_bonus_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Использованные бонусные баллы'),
        ),
    ]
