# Generated by Django 4.2 on 2024-06-26 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_order_used_bonus_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='used_bonus_points',
        ),
    ]
