# Generated by Django 4.2 on 2024-06-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_order_used_bonus_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusconfiguration',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='bonusconfiguration',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Порог бесплатной доставки'),
        ),
    ]
