# Generated by Django 4.2 on 2024-06-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_bonusconfiguration_delivery_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Стоимость доставки')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Порог бесплатной доставки')),
            ],
            options={
                'verbose_name': 'Конфигурация доставки',
                'verbose_name_plural': 'Конфигурации доставки',
            },
        ),
        migrations.RemoveField(
            model_name='bonusconfiguration',
            name='delivery_cost',
        ),
        migrations.RemoveField(
            model_name='bonusconfiguration',
            name='free_delivery_threshold',
        ),
    ]
