# Generated by Django 5.0.6 on 2024-06-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='apartment_number',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='intercom',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='street',
        ),
        migrations.AddField(
            model_name='user',
            name='is_retiree',
            field=models.BooleanField(default=False, verbose_name='Пенсионер'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='address',
            field=models.CharField(default=1, max_length=255, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
