# Generated by Django 5.0.6 on 2024-06-21 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_useraddress_apartment_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetireeCardPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='retiree_card_photos/', verbose_name='Фото пенсионерной карточки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiree_card_photos', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фото пенсионерной карточки',
                'verbose_name_plural': 'Фотографии пенсионерных карточек',
            },
        ),
    ]
