# Generated by Django 5.0.6 on 2024-06-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_retireecardphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='retiree_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='retiree_cards/', verbose_name='Оборотная сторона карточки пенсионера'),
        ),
        migrations.AddField(
            model_name='user',
            name='retiree_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='retiree_cards/', verbose_name='Лицевая сторона карточки пенсионера'),
        ),
        migrations.DeleteModel(
            name='RetireeCardPhoto',
        ),
    ]
