# Generated by Django 4.2 on 2024-06-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_retiree_approved',
            field=models.BooleanField(default=False, verbose_name='Прошел модерацию'),
        ),
    ]
