# Generated by Django 4.2 on 2024-06-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_user_name_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Бонусные баллы'),
        ),
    ]
